# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Users/gmonacho/.brew/Cellar/cmake/3.14.5/bin/cmake

# The command to remove a file.
RM = /Users/gmonacho/.brew/Cellar/cmake/3.14.5/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/gmonacho/Documents/101/libui

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/gmonacho/Documents/101/libui

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Users/gmonacho/.brew/Cellar/cmake/3.14.5/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Users/gmonacho/.brew/Cellar/cmake/3.14.5/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/gmonacho/Documents/101/libui/CMakeFiles /Users/gmonacho/Documents/101/libui/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/gmonacho/Documents/101/libui/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ui

# Build rule for target.
ui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ui
.PHONY : ui

# fast build rule for target.
ui/fast:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/build
.PHONY : ui/fast

src/button/ui_button.o: src/button/ui_button.c.o

.PHONY : src/button/ui_button.o

# target to build an object file
src/button/ui_button.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/button/ui_button.c.o
.PHONY : src/button/ui_button.c.o

src/button/ui_button.i: src/button/ui_button.c.i

.PHONY : src/button/ui_button.i

# target to preprocess a source file
src/button/ui_button.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/button/ui_button.c.i
.PHONY : src/button/ui_button.c.i

src/button/ui_button.s: src/button/ui_button.c.s

.PHONY : src/button/ui_button.s

# target to generate assembly for a file
src/button/ui_button.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/button/ui_button.c.s
.PHONY : src/button/ui_button.c.s

src/button/ui_simple_button.o: src/button/ui_simple_button.c.o

.PHONY : src/button/ui_simple_button.o

# target to build an object file
src/button/ui_simple_button.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/button/ui_simple_button.c.o
.PHONY : src/button/ui_simple_button.c.o

src/button/ui_simple_button.i: src/button/ui_simple_button.c.i

.PHONY : src/button/ui_simple_button.i

# target to preprocess a source file
src/button/ui_simple_button.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/button/ui_simple_button.c.i
.PHONY : src/button/ui_simple_button.c.i

src/button/ui_simple_button.s: src/button/ui_simple_button.c.s

.PHONY : src/button/ui_simple_button.s

# target to generate assembly for a file
src/button/ui_simple_button.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/button/ui_simple_button.c.s
.PHONY : src/button/ui_simple_button.c.s

src/button/ui_text_area.o: src/button/ui_text_area.c.o

.PHONY : src/button/ui_text_area.o

# target to build an object file
src/button/ui_text_area.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/button/ui_text_area.c.o
.PHONY : src/button/ui_text_area.c.o

src/button/ui_text_area.i: src/button/ui_text_area.c.i

.PHONY : src/button/ui_text_area.i

# target to preprocess a source file
src/button/ui_text_area.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/button/ui_text_area.c.i
.PHONY : src/button/ui_text_area.c.i

src/button/ui_text_area.s: src/button/ui_text_area.c.s

.PHONY : src/button/ui_text_area.s

# target to generate assembly for a file
src/button/ui_text_area.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/button/ui_text_area.c.s
.PHONY : src/button/ui_text_area.c.s

src/button/ui_text_entry_button.o: src/button/ui_text_entry_button.c.o

.PHONY : src/button/ui_text_entry_button.o

# target to build an object file
src/button/ui_text_entry_button.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/button/ui_text_entry_button.c.o
.PHONY : src/button/ui_text_entry_button.c.o

src/button/ui_text_entry_button.i: src/button/ui_text_entry_button.c.i

.PHONY : src/button/ui_text_entry_button.i

# target to preprocess a source file
src/button/ui_text_entry_button.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/button/ui_text_entry_button.c.i
.PHONY : src/button/ui_text_entry_button.c.i

src/button/ui_text_entry_button.s: src/button/ui_text_entry_button.c.s

.PHONY : src/button/ui_text_entry_button.s

# target to generate assembly for a file
src/button/ui_text_entry_button.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/button/ui_text_entry_button.c.s
.PHONY : src/button/ui_text_entry_button.c.s

src/draw/draw.o: src/draw/draw.c.o

.PHONY : src/draw/draw.o

# target to build an object file
src/draw/draw.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/draw/draw.c.o
.PHONY : src/draw/draw.c.o

src/draw/draw.i: src/draw/draw.c.i

.PHONY : src/draw/draw.i

# target to preprocess a source file
src/draw/draw.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/draw/draw.c.i
.PHONY : src/draw/draw.c.i

src/draw/draw.s: src/draw/draw.c.s

.PHONY : src/draw/draw.s

# target to generate assembly for a file
src/draw/draw.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/draw/draw.c.s
.PHONY : src/draw/draw.c.s

src/draw/draw_shape.o: src/draw/draw_shape.c.o

.PHONY : src/draw/draw_shape.o

# target to build an object file
src/draw/draw_shape.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/draw/draw_shape.c.o
.PHONY : src/draw/draw_shape.c.o

src/draw/draw_shape.i: src/draw/draw_shape.c.i

.PHONY : src/draw/draw_shape.i

# target to preprocess a source file
src/draw/draw_shape.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/draw/draw_shape.c.i
.PHONY : src/draw/draw_shape.c.i

src/draw/draw_shape.s: src/draw/draw_shape.c.s

.PHONY : src/draw/draw_shape.s

# target to generate assembly for a file
src/draw/draw_shape.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/draw/draw_shape.c.s
.PHONY : src/draw/draw_shape.c.s

src/event/ui_event.o: src/event/ui_event.c.o

.PHONY : src/event/ui_event.o

# target to build an object file
src/event/ui_event.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/event/ui_event.c.o
.PHONY : src/event/ui_event.c.o

src/event/ui_event.i: src/event/ui_event.c.i

.PHONY : src/event/ui_event.i

# target to preprocess a source file
src/event/ui_event.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/event/ui_event.c.i
.PHONY : src/event/ui_event.c.i

src/event/ui_event.s: src/event/ui_event.c.s

.PHONY : src/event/ui_event.s

# target to generate assembly for a file
src/event/ui_event.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/event/ui_event.c.s
.PHONY : src/event/ui_event.c.s

src/frame/ui_frame.o: src/frame/ui_frame.c.o

.PHONY : src/frame/ui_frame.o

# target to build an object file
src/frame/ui_frame.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/frame/ui_frame.c.o
.PHONY : src/frame/ui_frame.c.o

src/frame/ui_frame.i: src/frame/ui_frame.c.i

.PHONY : src/frame/ui_frame.i

# target to preprocess a source file
src/frame/ui_frame.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/frame/ui_frame.c.i
.PHONY : src/frame/ui_frame.c.i

src/frame/ui_frame.s: src/frame/ui_frame.c.s

.PHONY : src/frame/ui_frame.s

# target to generate assembly for a file
src/frame/ui_frame.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/frame/ui_frame.c.s
.PHONY : src/frame/ui_frame.c.s

src/frame/ui_simple_frame.o: src/frame/ui_simple_frame.c.o

.PHONY : src/frame/ui_simple_frame.o

# target to build an object file
src/frame/ui_simple_frame.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/frame/ui_simple_frame.c.o
.PHONY : src/frame/ui_simple_frame.c.o

src/frame/ui_simple_frame.i: src/frame/ui_simple_frame.c.i

.PHONY : src/frame/ui_simple_frame.i

# target to preprocess a source file
src/frame/ui_simple_frame.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/frame/ui_simple_frame.c.i
.PHONY : src/frame/ui_simple_frame.c.i

src/frame/ui_simple_frame.s: src/frame/ui_simple_frame.c.s

.PHONY : src/frame/ui_simple_frame.s

# target to generate assembly for a file
src/frame/ui_simple_frame.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/frame/ui_simple_frame.c.s
.PHONY : src/frame/ui_simple_frame.c.s

src/load_ui/ui_check_line_name.o: src/load_ui/ui_check_line_name.c.o

.PHONY : src/load_ui/ui_check_line_name.o

# target to build an object file
src/load_ui/ui_check_line_name.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_check_line_name.c.o
.PHONY : src/load_ui/ui_check_line_name.c.o

src/load_ui/ui_check_line_name.i: src/load_ui/ui_check_line_name.c.i

.PHONY : src/load_ui/ui_check_line_name.i

# target to preprocess a source file
src/load_ui/ui_check_line_name.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_check_line_name.c.i
.PHONY : src/load_ui/ui_check_line_name.c.i

src/load_ui/ui_check_line_name.s: src/load_ui/ui_check_line_name.c.s

.PHONY : src/load_ui/ui_check_line_name.s

# target to generate assembly for a file
src/load_ui/ui_check_line_name.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_check_line_name.c.s
.PHONY : src/load_ui/ui_check_line_name.c.s

src/load_ui/ui_general_get.o: src/load_ui/ui_general_get.c.o

.PHONY : src/load_ui/ui_general_get.o

# target to build an object file
src/load_ui/ui_general_get.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_general_get.c.o
.PHONY : src/load_ui/ui_general_get.c.o

src/load_ui/ui_general_get.i: src/load_ui/ui_general_get.c.i

.PHONY : src/load_ui/ui_general_get.i

# target to preprocess a source file
src/load_ui/ui_general_get.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_general_get.c.i
.PHONY : src/load_ui/ui_general_get.c.i

src/load_ui/ui_general_get.s: src/load_ui/ui_general_get.c.s

.PHONY : src/load_ui/ui_general_get.s

# target to generate assembly for a file
src/load_ui/ui_general_get.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_general_get.c.s
.PHONY : src/load_ui/ui_general_get.c.s

src/load_ui/ui_get_b_type.o: src/load_ui/ui_get_b_type.c.o

.PHONY : src/load_ui/ui_get_b_type.o

# target to build an object file
src/load_ui/ui_get_b_type.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_get_b_type.c.o
.PHONY : src/load_ui/ui_get_b_type.c.o

src/load_ui/ui_get_b_type.i: src/load_ui/ui_get_b_type.c.i

.PHONY : src/load_ui/ui_get_b_type.i

# target to preprocess a source file
src/load_ui/ui_get_b_type.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_get_b_type.c.i
.PHONY : src/load_ui/ui_get_b_type.c.i

src/load_ui/ui_get_b_type.s: src/load_ui/ui_get_b_type.c.s

.PHONY : src/load_ui/ui_get_b_type.s

# target to generate assembly for a file
src/load_ui/ui_get_b_type.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_get_b_type.c.s
.PHONY : src/load_ui/ui_get_b_type.c.s

src/load_ui/ui_get_flags.o: src/load_ui/ui_get_flags.c.o

.PHONY : src/load_ui/ui_get_flags.o

# target to build an object file
src/load_ui/ui_get_flags.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_get_flags.c.o
.PHONY : src/load_ui/ui_get_flags.c.o

src/load_ui/ui_get_flags.i: src/load_ui/ui_get_flags.c.i

.PHONY : src/load_ui/ui_get_flags.i

# target to preprocess a source file
src/load_ui/ui_get_flags.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_get_flags.c.i
.PHONY : src/load_ui/ui_get_flags.c.i

src/load_ui/ui_get_flags.s: src/load_ui/ui_get_flags.c.s

.PHONY : src/load_ui/ui_get_flags.s

# target to generate assembly for a file
src/load_ui/ui_get_flags.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_get_flags.c.s
.PHONY : src/load_ui/ui_get_flags.c.s

src/load_ui/ui_get_type.o: src/load_ui/ui_get_type.c.o

.PHONY : src/load_ui/ui_get_type.o

# target to build an object file
src/load_ui/ui_get_type.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_get_type.c.o
.PHONY : src/load_ui/ui_get_type.c.o

src/load_ui/ui_get_type.i: src/load_ui/ui_get_type.c.i

.PHONY : src/load_ui/ui_get_type.i

# target to preprocess a source file
src/load_ui/ui_get_type.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_get_type.c.i
.PHONY : src/load_ui/ui_get_type.c.i

src/load_ui/ui_get_type.s: src/load_ui/ui_get_type.c.s

.PHONY : src/load_ui/ui_get_type.s

# target to generate assembly for a file
src/load_ui/ui_get_type.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_get_type.c.s
.PHONY : src/load_ui/ui_get_type.c.s

src/load_ui/ui_load.o: src/load_ui/ui_load.c.o

.PHONY : src/load_ui/ui_load.o

# target to build an object file
src/load_ui/ui_load.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_load.c.o
.PHONY : src/load_ui/ui_load.c.o

src/load_ui/ui_load.i: src/load_ui/ui_load.c.i

.PHONY : src/load_ui/ui_load.i

# target to preprocess a source file
src/load_ui/ui_load.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_load.c.i
.PHONY : src/load_ui/ui_load.c.i

src/load_ui/ui_load.s: src/load_ui/ui_load.c.s

.PHONY : src/load_ui/ui_load.s

# target to generate assembly for a file
src/load_ui/ui_load.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_load.c.s
.PHONY : src/load_ui/ui_load.c.s

src/load_ui/ui_parse_button.o: src/load_ui/ui_parse_button.c.o

.PHONY : src/load_ui/ui_parse_button.o

# target to build an object file
src/load_ui/ui_parse_button.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_parse_button.c.o
.PHONY : src/load_ui/ui_parse_button.c.o

src/load_ui/ui_parse_button.i: src/load_ui/ui_parse_button.c.i

.PHONY : src/load_ui/ui_parse_button.i

# target to preprocess a source file
src/load_ui/ui_parse_button.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_parse_button.c.i
.PHONY : src/load_ui/ui_parse_button.c.i

src/load_ui/ui_parse_button.s: src/load_ui/ui_parse_button.c.s

.PHONY : src/load_ui/ui_parse_button.s

# target to generate assembly for a file
src/load_ui/ui_parse_button.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_parse_button.c.s
.PHONY : src/load_ui/ui_parse_button.c.s

src/load_ui/ui_parse_buttons.o: src/load_ui/ui_parse_buttons.c.o

.PHONY : src/load_ui/ui_parse_buttons.o

# target to build an object file
src/load_ui/ui_parse_buttons.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_parse_buttons.c.o
.PHONY : src/load_ui/ui_parse_buttons.c.o

src/load_ui/ui_parse_buttons.i: src/load_ui/ui_parse_buttons.c.i

.PHONY : src/load_ui/ui_parse_buttons.i

# target to preprocess a source file
src/load_ui/ui_parse_buttons.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_parse_buttons.c.i
.PHONY : src/load_ui/ui_parse_buttons.c.i

src/load_ui/ui_parse_buttons.s: src/load_ui/ui_parse_buttons.c.s

.PHONY : src/load_ui/ui_parse_buttons.s

# target to generate assembly for a file
src/load_ui/ui_parse_buttons.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_parse_buttons.c.s
.PHONY : src/load_ui/ui_parse_buttons.c.s

src/load_ui/ui_parse_frame.o: src/load_ui/ui_parse_frame.c.o

.PHONY : src/load_ui/ui_parse_frame.o

# target to build an object file
src/load_ui/ui_parse_frame.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_parse_frame.c.o
.PHONY : src/load_ui/ui_parse_frame.c.o

src/load_ui/ui_parse_frame.i: src/load_ui/ui_parse_frame.c.i

.PHONY : src/load_ui/ui_parse_frame.i

# target to preprocess a source file
src/load_ui/ui_parse_frame.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_parse_frame.c.i
.PHONY : src/load_ui/ui_parse_frame.c.i

src/load_ui/ui_parse_frame.s: src/load_ui/ui_parse_frame.c.s

.PHONY : src/load_ui/ui_parse_frame.s

# target to generate assembly for a file
src/load_ui/ui_parse_frame.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_parse_frame.c.s
.PHONY : src/load_ui/ui_parse_frame.c.s

src/load_ui/ui_parse_frame_data.o: src/load_ui/ui_parse_frame_data.c.o

.PHONY : src/load_ui/ui_parse_frame_data.o

# target to build an object file
src/load_ui/ui_parse_frame_data.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_parse_frame_data.c.o
.PHONY : src/load_ui/ui_parse_frame_data.c.o

src/load_ui/ui_parse_frame_data.i: src/load_ui/ui_parse_frame_data.c.i

.PHONY : src/load_ui/ui_parse_frame_data.i

# target to preprocess a source file
src/load_ui/ui_parse_frame_data.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_parse_frame_data.c.i
.PHONY : src/load_ui/ui_parse_frame_data.c.i

src/load_ui/ui_parse_frame_data.s: src/load_ui/ui_parse_frame_data.c.s

.PHONY : src/load_ui/ui_parse_frame_data.s

# target to generate assembly for a file
src/load_ui/ui_parse_frame_data.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_parse_frame_data.c.s
.PHONY : src/load_ui/ui_parse_frame_data.c.s

src/load_ui/ui_parse_simple_button.o: src/load_ui/ui_parse_simple_button.c.o

.PHONY : src/load_ui/ui_parse_simple_button.o

# target to build an object file
src/load_ui/ui_parse_simple_button.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_parse_simple_button.c.o
.PHONY : src/load_ui/ui_parse_simple_button.c.o

src/load_ui/ui_parse_simple_button.i: src/load_ui/ui_parse_simple_button.c.i

.PHONY : src/load_ui/ui_parse_simple_button.i

# target to preprocess a source file
src/load_ui/ui_parse_simple_button.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_parse_simple_button.c.i
.PHONY : src/load_ui/ui_parse_simple_button.c.i

src/load_ui/ui_parse_simple_button.s: src/load_ui/ui_parse_simple_button.c.s

.PHONY : src/load_ui/ui_parse_simple_button.s

# target to generate assembly for a file
src/load_ui/ui_parse_simple_button.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_parse_simple_button.c.s
.PHONY : src/load_ui/ui_parse_simple_button.c.s

src/load_ui/ui_parse_simple_frame.o: src/load_ui/ui_parse_simple_frame.c.o

.PHONY : src/load_ui/ui_parse_simple_frame.o

# target to build an object file
src/load_ui/ui_parse_simple_frame.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_parse_simple_frame.c.o
.PHONY : src/load_ui/ui_parse_simple_frame.c.o

src/load_ui/ui_parse_simple_frame.i: src/load_ui/ui_parse_simple_frame.c.i

.PHONY : src/load_ui/ui_parse_simple_frame.i

# target to preprocess a source file
src/load_ui/ui_parse_simple_frame.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_parse_simple_frame.c.i
.PHONY : src/load_ui/ui_parse_simple_frame.c.i

src/load_ui/ui_parse_simple_frame.s: src/load_ui/ui_parse_simple_frame.c.s

.PHONY : src/load_ui/ui_parse_simple_frame.s

# target to generate assembly for a file
src/load_ui/ui_parse_simple_frame.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_parse_simple_frame.c.s
.PHONY : src/load_ui/ui_parse_simple_frame.c.s

src/load_ui/ui_parse_text_area.o: src/load_ui/ui_parse_text_area.c.o

.PHONY : src/load_ui/ui_parse_text_area.o

# target to build an object file
src/load_ui/ui_parse_text_area.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_parse_text_area.c.o
.PHONY : src/load_ui/ui_parse_text_area.c.o

src/load_ui/ui_parse_text_area.i: src/load_ui/ui_parse_text_area.c.i

.PHONY : src/load_ui/ui_parse_text_area.i

# target to preprocess a source file
src/load_ui/ui_parse_text_area.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_parse_text_area.c.i
.PHONY : src/load_ui/ui_parse_text_area.c.i

src/load_ui/ui_parse_text_area.s: src/load_ui/ui_parse_text_area.c.s

.PHONY : src/load_ui/ui_parse_text_area.s

# target to generate assembly for a file
src/load_ui/ui_parse_text_area.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_parse_text_area.c.s
.PHONY : src/load_ui/ui_parse_text_area.c.s

src/load_ui/ui_parse_text_entry_button.o: src/load_ui/ui_parse_text_entry_button.c.o

.PHONY : src/load_ui/ui_parse_text_entry_button.o

# target to build an object file
src/load_ui/ui_parse_text_entry_button.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_parse_text_entry_button.c.o
.PHONY : src/load_ui/ui_parse_text_entry_button.c.o

src/load_ui/ui_parse_text_entry_button.i: src/load_ui/ui_parse_text_entry_button.c.i

.PHONY : src/load_ui/ui_parse_text_entry_button.i

# target to preprocess a source file
src/load_ui/ui_parse_text_entry_button.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_parse_text_entry_button.c.i
.PHONY : src/load_ui/ui_parse_text_entry_button.c.i

src/load_ui/ui_parse_text_entry_button.s: src/load_ui/ui_parse_text_entry_button.c.s

.PHONY : src/load_ui/ui_parse_text_entry_button.s

# target to generate assembly for a file
src/load_ui/ui_parse_text_entry_button.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_parse_text_entry_button.c.s
.PHONY : src/load_ui/ui_parse_text_entry_button.c.s

src/load_ui/ui_parse_text_entry_cut.o: src/load_ui/ui_parse_text_entry_cut.c.o

.PHONY : src/load_ui/ui_parse_text_entry_cut.o

# target to build an object file
src/load_ui/ui_parse_text_entry_cut.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_parse_text_entry_cut.c.o
.PHONY : src/load_ui/ui_parse_text_entry_cut.c.o

src/load_ui/ui_parse_text_entry_cut.i: src/load_ui/ui_parse_text_entry_cut.c.i

.PHONY : src/load_ui/ui_parse_text_entry_cut.i

# target to preprocess a source file
src/load_ui/ui_parse_text_entry_cut.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_parse_text_entry_cut.c.i
.PHONY : src/load_ui/ui_parse_text_entry_cut.c.i

src/load_ui/ui_parse_text_entry_cut.s: src/load_ui/ui_parse_text_entry_cut.c.s

.PHONY : src/load_ui/ui_parse_text_entry_cut.s

# target to generate assembly for a file
src/load_ui/ui_parse_text_entry_cut.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_parse_text_entry_cut.c.s
.PHONY : src/load_ui/ui_parse_text_entry_cut.c.s

src/load_ui/ui_parse_texture.o: src/load_ui/ui_parse_texture.c.o

.PHONY : src/load_ui/ui_parse_texture.o

# target to build an object file
src/load_ui/ui_parse_texture.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_parse_texture.c.o
.PHONY : src/load_ui/ui_parse_texture.c.o

src/load_ui/ui_parse_texture.i: src/load_ui/ui_parse_texture.c.i

.PHONY : src/load_ui/ui_parse_texture.i

# target to preprocess a source file
src/load_ui/ui_parse_texture.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_parse_texture.c.i
.PHONY : src/load_ui/ui_parse_texture.c.i

src/load_ui/ui_parse_texture.s: src/load_ui/ui_parse_texture.c.s

.PHONY : src/load_ui/ui_parse_texture.s

# target to generate assembly for a file
src/load_ui/ui_parse_texture.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_parse_texture.c.s
.PHONY : src/load_ui/ui_parse_texture.c.s

src/load_ui/ui_parse_type.o: src/load_ui/ui_parse_type.c.o

.PHONY : src/load_ui/ui_parse_type.o

# target to build an object file
src/load_ui/ui_parse_type.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_parse_type.c.o
.PHONY : src/load_ui/ui_parse_type.c.o

src/load_ui/ui_parse_type.i: src/load_ui/ui_parse_type.c.i

.PHONY : src/load_ui/ui_parse_type.i

# target to preprocess a source file
src/load_ui/ui_parse_type.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_parse_type.c.i
.PHONY : src/load_ui/ui_parse_type.c.i

src/load_ui/ui_parse_type.s: src/load_ui/ui_parse_type.c.s

.PHONY : src/load_ui/ui_parse_type.s

# target to generate assembly for a file
src/load_ui/ui_parse_type.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/load_ui/ui_parse_type.c.s
.PHONY : src/load_ui/ui_parse_type.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/main.c.s
.PHONY : src/main.c.s

src/shape/ui_rect.o: src/shape/ui_rect.c.o

.PHONY : src/shape/ui_rect.o

# target to build an object file
src/shape/ui_rect.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/shape/ui_rect.c.o
.PHONY : src/shape/ui_rect.c.o

src/shape/ui_rect.i: src/shape/ui_rect.c.i

.PHONY : src/shape/ui_rect.i

# target to preprocess a source file
src/shape/ui_rect.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/shape/ui_rect.c.i
.PHONY : src/shape/ui_rect.c.i

src/shape/ui_rect.s: src/shape/ui_rect.c.s

.PHONY : src/shape/ui_rect.s

# target to generate assembly for a file
src/shape/ui_rect.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/shape/ui_rect.c.s
.PHONY : src/shape/ui_rect.c.s

src/texture/ui_draw_one_line_return.o: src/texture/ui_draw_one_line_return.c.o

.PHONY : src/texture/ui_draw_one_line_return.o

# target to build an object file
src/texture/ui_draw_one_line_return.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/texture/ui_draw_one_line_return.c.o
.PHONY : src/texture/ui_draw_one_line_return.c.o

src/texture/ui_draw_one_line_return.i: src/texture/ui_draw_one_line_return.c.i

.PHONY : src/texture/ui_draw_one_line_return.i

# target to preprocess a source file
src/texture/ui_draw_one_line_return.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/texture/ui_draw_one_line_return.c.i
.PHONY : src/texture/ui_draw_one_line_return.c.i

src/texture/ui_draw_one_line_return.s: src/texture/ui_draw_one_line_return.c.s

.PHONY : src/texture/ui_draw_one_line_return.s

# target to generate assembly for a file
src/texture/ui_draw_one_line_return.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/texture/ui_draw_one_line_return.c.s
.PHONY : src/texture/ui_draw_one_line_return.c.s

src/texture/ui_draw_text_line.o: src/texture/ui_draw_text_line.c.o

.PHONY : src/texture/ui_draw_text_line.o

# target to build an object file
src/texture/ui_draw_text_line.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/texture/ui_draw_text_line.c.o
.PHONY : src/texture/ui_draw_text_line.c.o

src/texture/ui_draw_text_line.i: src/texture/ui_draw_text_line.c.i

.PHONY : src/texture/ui_draw_text_line.i

# target to preprocess a source file
src/texture/ui_draw_text_line.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/texture/ui_draw_text_line.c.i
.PHONY : src/texture/ui_draw_text_line.c.i

src/texture/ui_draw_text_line.s: src/texture/ui_draw_text_line.c.s

.PHONY : src/texture/ui_draw_text_line.s

# target to generate assembly for a file
src/texture/ui_draw_text_line.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/texture/ui_draw_text_line.c.s
.PHONY : src/texture/ui_draw_text_line.c.s

src/texture/ui_draw_text_line_return.o: src/texture/ui_draw_text_line_return.c.o

.PHONY : src/texture/ui_draw_text_line_return.o

# target to build an object file
src/texture/ui_draw_text_line_return.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/texture/ui_draw_text_line_return.c.o
.PHONY : src/texture/ui_draw_text_line_return.c.o

src/texture/ui_draw_text_line_return.i: src/texture/ui_draw_text_line_return.c.i

.PHONY : src/texture/ui_draw_text_line_return.i

# target to preprocess a source file
src/texture/ui_draw_text_line_return.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/texture/ui_draw_text_line_return.c.i
.PHONY : src/texture/ui_draw_text_line_return.c.i

src/texture/ui_draw_text_line_return.s: src/texture/ui_draw_text_line_return.c.s

.PHONY : src/texture/ui_draw_text_line_return.s

# target to generate assembly for a file
src/texture/ui_draw_text_line_return.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/texture/ui_draw_text_line_return.c.s
.PHONY : src/texture/ui_draw_text_line_return.c.s

src/texture/ui_draw_text_rect.o: src/texture/ui_draw_text_rect.c.o

.PHONY : src/texture/ui_draw_text_rect.o

# target to build an object file
src/texture/ui_draw_text_rect.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/texture/ui_draw_text_rect.c.o
.PHONY : src/texture/ui_draw_text_rect.c.o

src/texture/ui_draw_text_rect.i: src/texture/ui_draw_text_rect.c.i

.PHONY : src/texture/ui_draw_text_rect.i

# target to preprocess a source file
src/texture/ui_draw_text_rect.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/texture/ui_draw_text_rect.c.i
.PHONY : src/texture/ui_draw_text_rect.c.i

src/texture/ui_draw_text_rect.s: src/texture/ui_draw_text_rect.c.s

.PHONY : src/texture/ui_draw_text_rect.s

# target to generate assembly for a file
src/texture/ui_draw_text_rect.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/texture/ui_draw_text_rect.c.s
.PHONY : src/texture/ui_draw_text_rect.c.s

src/texture/ui_free_texture_set.o: src/texture/ui_free_texture_set.c.o

.PHONY : src/texture/ui_free_texture_set.o

# target to build an object file
src/texture/ui_free_texture_set.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/texture/ui_free_texture_set.c.o
.PHONY : src/texture/ui_free_texture_set.c.o

src/texture/ui_free_texture_set.i: src/texture/ui_free_texture_set.c.i

.PHONY : src/texture/ui_free_texture_set.i

# target to preprocess a source file
src/texture/ui_free_texture_set.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/texture/ui_free_texture_set.c.i
.PHONY : src/texture/ui_free_texture_set.c.i

src/texture/ui_free_texture_set.s: src/texture/ui_free_texture_set.c.s

.PHONY : src/texture/ui_free_texture_set.s

# target to generate assembly for a file
src/texture/ui_free_texture_set.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/texture/ui_free_texture_set.c.s
.PHONY : src/texture/ui_free_texture_set.c.s

src/texture/ui_renderer.o: src/texture/ui_renderer.c.o

.PHONY : src/texture/ui_renderer.o

# target to build an object file
src/texture/ui_renderer.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/texture/ui_renderer.c.o
.PHONY : src/texture/ui_renderer.c.o

src/texture/ui_renderer.i: src/texture/ui_renderer.c.i

.PHONY : src/texture/ui_renderer.i

# target to preprocess a source file
src/texture/ui_renderer.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/texture/ui_renderer.c.i
.PHONY : src/texture/ui_renderer.c.i

src/texture/ui_renderer.s: src/texture/ui_renderer.c.s

.PHONY : src/texture/ui_renderer.s

# target to generate assembly for a file
src/texture/ui_renderer.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/texture/ui_renderer.c.s
.PHONY : src/texture/ui_renderer.c.s

src/texture/ui_text.o: src/texture/ui_text.c.o

.PHONY : src/texture/ui_text.o

# target to build an object file
src/texture/ui_text.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/texture/ui_text.c.o
.PHONY : src/texture/ui_text.c.o

src/texture/ui_text.i: src/texture/ui_text.c.i

.PHONY : src/texture/ui_text.i

# target to preprocess a source file
src/texture/ui_text.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/texture/ui_text.c.i
.PHONY : src/texture/ui_text.c.i

src/texture/ui_text.s: src/texture/ui_text.c.s

.PHONY : src/texture/ui_text.s

# target to generate assembly for a file
src/texture/ui_text.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/texture/ui_text.c.s
.PHONY : src/texture/ui_text.c.s

src/texture/ui_texture.o: src/texture/ui_texture.c.o

.PHONY : src/texture/ui_texture.o

# target to build an object file
src/texture/ui_texture.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/texture/ui_texture.c.o
.PHONY : src/texture/ui_texture.c.o

src/texture/ui_texture.i: src/texture/ui_texture.c.i

.PHONY : src/texture/ui_texture.i

# target to preprocess a source file
src/texture/ui_texture.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/texture/ui_texture.c.i
.PHONY : src/texture/ui_texture.c.i

src/texture/ui_texture.s: src/texture/ui_texture.c.s

.PHONY : src/texture/ui_texture.s

# target to generate assembly for a file
src/texture/ui_texture.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/texture/ui_texture.c.s
.PHONY : src/texture/ui_texture.c.s

src/texture/ui_texture_list.o: src/texture/ui_texture_list.c.o

.PHONY : src/texture/ui_texture_list.o

# target to build an object file
src/texture/ui_texture_list.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/texture/ui_texture_list.c.o
.PHONY : src/texture/ui_texture_list.c.o

src/texture/ui_texture_list.i: src/texture/ui_texture_list.c.i

.PHONY : src/texture/ui_texture_list.i

# target to preprocess a source file
src/texture/ui_texture_list.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/texture/ui_texture_list.c.i
.PHONY : src/texture/ui_texture_list.c.i

src/texture/ui_texture_list.s: src/texture/ui_texture_list.c.s

.PHONY : src/texture/ui_texture_list.s

# target to generate assembly for a file
src/texture/ui_texture_list.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/texture/ui_texture_list.c.s
.PHONY : src/texture/ui_texture_list.c.s

src/ui_error.o: src/ui_error.c.o

.PHONY : src/ui_error.o

# target to build an object file
src/ui_error.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/ui_error.c.o
.PHONY : src/ui_error.c.o

src/ui_error.i: src/ui_error.c.i

.PHONY : src/ui_error.i

# target to preprocess a source file
src/ui_error.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/ui_error.c.i
.PHONY : src/ui_error.c.i

src/ui_error.s: src/ui_error.c.s

.PHONY : src/ui_error.s

# target to generate assembly for a file
src/ui_error.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/ui_error.c.s
.PHONY : src/ui_error.c.s

src/ui_init.o: src/ui_init.c.o

.PHONY : src/ui_init.o

# target to build an object file
src/ui_init.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/ui_init.c.o
.PHONY : src/ui_init.c.o

src/ui_init.i: src/ui_init.c.i

.PHONY : src/ui_init.i

# target to preprocess a source file
src/ui_init.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/ui_init.c.i
.PHONY : src/ui_init.c.i

src/ui_init.s: src/ui_init.c.s

.PHONY : src/ui_init.s

# target to generate assembly for a file
src/ui_init.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/ui_init.c.s
.PHONY : src/ui_init.c.s

src/win/ui.o: src/win/ui.c.o

.PHONY : src/win/ui.o

# target to build an object file
src/win/ui.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui.c.o
.PHONY : src/win/ui.c.o

src/win/ui.i: src/win/ui.c.i

.PHONY : src/win/ui.i

# target to preprocess a source file
src/win/ui.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui.c.i
.PHONY : src/win/ui.c.i

src/win/ui.s: src/win/ui.c.s

.PHONY : src/win/ui.s

# target to generate assembly for a file
src/win/ui.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui.c.s
.PHONY : src/win/ui.c.s

src/win/ui_call_button_function.o: src/win/ui_call_button_function.c.o

.PHONY : src/win/ui_call_button_function.o

# target to build an object file
src/win/ui_call_button_function.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_call_button_function.c.o
.PHONY : src/win/ui_call_button_function.c.o

src/win/ui_call_button_function.i: src/win/ui_call_button_function.c.i

.PHONY : src/win/ui_call_button_function.i

# target to preprocess a source file
src/win/ui_call_button_function.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_call_button_function.c.i
.PHONY : src/win/ui_call_button_function.c.i

src/win/ui_call_button_function.s: src/win/ui_call_button_function.c.s

.PHONY : src/win/ui_call_button_function.s

# target to generate assembly for a file
src/win/ui_call_button_function.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_call_button_function.c.s
.PHONY : src/win/ui_call_button_function.c.s

src/win/ui_display_buttons.o: src/win/ui_display_buttons.c.o

.PHONY : src/win/ui_display_buttons.o

# target to build an object file
src/win/ui_display_buttons.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_display_buttons.c.o
.PHONY : src/win/ui_display_buttons.c.o

src/win/ui_display_buttons.i: src/win/ui_display_buttons.c.i

.PHONY : src/win/ui_display_buttons.i

# target to preprocess a source file
src/win/ui_display_buttons.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_display_buttons.c.i
.PHONY : src/win/ui_display_buttons.c.i

src/win/ui_display_buttons.s: src/win/ui_display_buttons.c.s

.PHONY : src/win/ui_display_buttons.s

# target to generate assembly for a file
src/win/ui_display_buttons.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_display_buttons.c.s
.PHONY : src/win/ui_display_buttons.c.s

src/win/ui_display_frames.o: src/win/ui_display_frames.c.o

.PHONY : src/win/ui_display_frames.o

# target to build an object file
src/win/ui_display_frames.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_display_frames.c.o
.PHONY : src/win/ui_display_frames.c.o

src/win/ui_display_frames.i: src/win/ui_display_frames.c.i

.PHONY : src/win/ui_display_frames.i

# target to preprocess a source file
src/win/ui_display_frames.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_display_frames.c.i
.PHONY : src/win/ui_display_frames.c.i

src/win/ui_display_frames.s: src/win/ui_display_frames.c.s

.PHONY : src/win/ui_display_frames.s

# target to generate assembly for a file
src/win/ui_display_frames.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_display_frames.c.s
.PHONY : src/win/ui_display_frames.c.s

src/win/ui_display_simple.o: src/win/ui_display_simple.c.o

.PHONY : src/win/ui_display_simple.o

# target to build an object file
src/win/ui_display_simple.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_display_simple.c.o
.PHONY : src/win/ui_display_simple.c.o

src/win/ui_display_simple.i: src/win/ui_display_simple.c.i

.PHONY : src/win/ui_display_simple.i

# target to preprocess a source file
src/win/ui_display_simple.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_display_simple.c.i
.PHONY : src/win/ui_display_simple.c.i

src/win/ui_display_simple.s: src/win/ui_display_simple.c.s

.PHONY : src/win/ui_display_simple.s

# target to generate assembly for a file
src/win/ui_display_simple.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_display_simple.c.s
.PHONY : src/win/ui_display_simple.c.s

src/win/ui_display_text_area.o: src/win/ui_display_text_area.c.o

.PHONY : src/win/ui_display_text_area.o

# target to build an object file
src/win/ui_display_text_area.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_display_text_area.c.o
.PHONY : src/win/ui_display_text_area.c.o

src/win/ui_display_text_area.i: src/win/ui_display_text_area.c.i

.PHONY : src/win/ui_display_text_area.i

# target to preprocess a source file
src/win/ui_display_text_area.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_display_text_area.c.i
.PHONY : src/win/ui_display_text_area.c.i

src/win/ui_display_text_area.s: src/win/ui_display_text_area.c.s

.PHONY : src/win/ui_display_text_area.s

# target to generate assembly for a file
src/win/ui_display_text_area.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_display_text_area.c.s
.PHONY : src/win/ui_display_text_area.c.s

src/win/ui_display_text_entry.o: src/win/ui_display_text_entry.c.o

.PHONY : src/win/ui_display_text_entry.o

# target to build an object file
src/win/ui_display_text_entry.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_display_text_entry.c.o
.PHONY : src/win/ui_display_text_entry.c.o

src/win/ui_display_text_entry.i: src/win/ui_display_text_entry.c.i

.PHONY : src/win/ui_display_text_entry.i

# target to preprocess a source file
src/win/ui_display_text_entry.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_display_text_entry.c.i
.PHONY : src/win/ui_display_text_entry.c.i

src/win/ui_display_text_entry.s: src/win/ui_display_text_entry.c.s

.PHONY : src/win/ui_display_text_entry.s

# target to generate assembly for a file
src/win/ui_display_text_entry.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_display_text_entry.c.s
.PHONY : src/win/ui_display_text_entry.c.s

src/win/ui_get_side_rect.o: src/win/ui_get_side_rect.c.o

.PHONY : src/win/ui_get_side_rect.o

# target to build an object file
src/win/ui_get_side_rect.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_get_side_rect.c.o
.PHONY : src/win/ui_get_side_rect.c.o

src/win/ui_get_side_rect.i: src/win/ui_get_side_rect.c.i

.PHONY : src/win/ui_get_side_rect.i

# target to preprocess a source file
src/win/ui_get_side_rect.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_get_side_rect.c.i
.PHONY : src/win/ui_get_side_rect.c.i

src/win/ui_get_side_rect.s: src/win/ui_get_side_rect.c.s

.PHONY : src/win/ui_get_side_rect.s

# target to generate assembly for a file
src/win/ui_get_side_rect.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_get_side_rect.c.s
.PHONY : src/win/ui_get_side_rect.c.s

src/win/ui_mouse.o: src/win/ui_mouse.c.o

.PHONY : src/win/ui_mouse.o

# target to build an object file
src/win/ui_mouse.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_mouse.c.o
.PHONY : src/win/ui_mouse.c.o

src/win/ui_mouse.i: src/win/ui_mouse.c.i

.PHONY : src/win/ui_mouse.i

# target to preprocess a source file
src/win/ui_mouse.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_mouse.c.i
.PHONY : src/win/ui_mouse.c.i

src/win/ui_mouse.s: src/win/ui_mouse.c.s

.PHONY : src/win/ui_mouse.s

# target to generate assembly for a file
src/win/ui_mouse.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_mouse.c.s
.PHONY : src/win/ui_mouse.c.s

src/win/ui_resolve_buttons_event.o: src/win/ui_resolve_buttons_event.c.o

.PHONY : src/win/ui_resolve_buttons_event.o

# target to build an object file
src/win/ui_resolve_buttons_event.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_resolve_buttons_event.c.o
.PHONY : src/win/ui_resolve_buttons_event.c.o

src/win/ui_resolve_buttons_event.i: src/win/ui_resolve_buttons_event.c.i

.PHONY : src/win/ui_resolve_buttons_event.i

# target to preprocess a source file
src/win/ui_resolve_buttons_event.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_resolve_buttons_event.c.i
.PHONY : src/win/ui_resolve_buttons_event.c.i

src/win/ui_resolve_buttons_event.s: src/win/ui_resolve_buttons_event.c.s

.PHONY : src/win/ui_resolve_buttons_event.s

# target to generate assembly for a file
src/win/ui_resolve_buttons_event.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_resolve_buttons_event.c.s
.PHONY : src/win/ui_resolve_buttons_event.c.s

src/win/ui_resolve_text_entry_button.o: src/win/ui_resolve_text_entry_button.c.o

.PHONY : src/win/ui_resolve_text_entry_button.o

# target to build an object file
src/win/ui_resolve_text_entry_button.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_resolve_text_entry_button.c.o
.PHONY : src/win/ui_resolve_text_entry_button.c.o

src/win/ui_resolve_text_entry_button.i: src/win/ui_resolve_text_entry_button.c.i

.PHONY : src/win/ui_resolve_text_entry_button.i

# target to preprocess a source file
src/win/ui_resolve_text_entry_button.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_resolve_text_entry_button.c.i
.PHONY : src/win/ui_resolve_text_entry_button.c.i

src/win/ui_resolve_text_entry_button.s: src/win/ui_resolve_text_entry_button.c.s

.PHONY : src/win/ui_resolve_text_entry_button.s

# target to generate assembly for a file
src/win/ui_resolve_text_entry_button.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_resolve_text_entry_button.c.s
.PHONY : src/win/ui_resolve_text_entry_button.c.s

src/win/ui_set_button_function.o: src/win/ui_set_button_function.c.o

.PHONY : src/win/ui_set_button_function.o

# target to build an object file
src/win/ui_set_button_function.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_set_button_function.c.o
.PHONY : src/win/ui_set_button_function.c.o

src/win/ui_set_button_function.i: src/win/ui_set_button_function.c.i

.PHONY : src/win/ui_set_button_function.i

# target to preprocess a source file
src/win/ui_set_button_function.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_set_button_function.c.i
.PHONY : src/win/ui_set_button_function.c.i

src/win/ui_set_button_function.s: src/win/ui_set_button_function.c.s

.PHONY : src/win/ui_set_button_function.s

# target to generate assembly for a file
src/win/ui_set_button_function.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_set_button_function.c.s
.PHONY : src/win/ui_set_button_function.c.s

src/win/ui_update_buttons.o: src/win/ui_update_buttons.c.o

.PHONY : src/win/ui_update_buttons.o

# target to build an object file
src/win/ui_update_buttons.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_update_buttons.c.o
.PHONY : src/win/ui_update_buttons.c.o

src/win/ui_update_buttons.i: src/win/ui_update_buttons.c.i

.PHONY : src/win/ui_update_buttons.i

# target to preprocess a source file
src/win/ui_update_buttons.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_update_buttons.c.i
.PHONY : src/win/ui_update_buttons.c.i

src/win/ui_update_buttons.s: src/win/ui_update_buttons.c.s

.PHONY : src/win/ui_update_buttons.s

# target to generate assembly for a file
src/win/ui_update_buttons.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_update_buttons.c.s
.PHONY : src/win/ui_update_buttons.c.s

src/win/ui_update_frames.o: src/win/ui_update_frames.c.o

.PHONY : src/win/ui_update_frames.o

# target to build an object file
src/win/ui_update_frames.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_update_frames.c.o
.PHONY : src/win/ui_update_frames.c.o

src/win/ui_update_frames.i: src/win/ui_update_frames.c.i

.PHONY : src/win/ui_update_frames.i

# target to preprocess a source file
src/win/ui_update_frames.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_update_frames.c.i
.PHONY : src/win/ui_update_frames.c.i

src/win/ui_update_frames.s: src/win/ui_update_frames.c.s

.PHONY : src/win/ui_update_frames.s

# target to generate assembly for a file
src/win/ui_update_frames.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_update_frames.c.s
.PHONY : src/win/ui_update_frames.c.s

src/win/ui_win.o: src/win/ui_win.c.o

.PHONY : src/win/ui_win.o

# target to build an object file
src/win/ui_win.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_win.c.o
.PHONY : src/win/ui_win.c.o

src/win/ui_win.i: src/win/ui_win.c.i

.PHONY : src/win/ui_win.i

# target to preprocess a source file
src/win/ui_win.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_win.c.i
.PHONY : src/win/ui_win.c.i

src/win/ui_win.s: src/win/ui_win.c.s

.PHONY : src/win/ui_win.s

# target to generate assembly for a file
src/win/ui_win.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_win.c.s
.PHONY : src/win/ui_win.c.s

src/win/ui_win_size.o: src/win/ui_win_size.c.o

.PHONY : src/win/ui_win_size.o

# target to build an object file
src/win/ui_win_size.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_win_size.c.o
.PHONY : src/win/ui_win_size.c.o

src/win/ui_win_size.i: src/win/ui_win_size.c.i

.PHONY : src/win/ui_win_size.i

# target to preprocess a source file
src/win/ui_win_size.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_win_size.c.i
.PHONY : src/win/ui_win_size.c.i

src/win/ui_win_size.s: src/win/ui_win_size.c.s

.PHONY : src/win/ui_win_size.s

# target to generate assembly for a file
src/win/ui_win_size.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_win_size.c.s
.PHONY : src/win/ui_win_size.c.s

src/win/ui_win_update_ui.o: src/win/ui_win_update_ui.c.o

.PHONY : src/win/ui_win_update_ui.o

# target to build an object file
src/win/ui_win_update_ui.c.o:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_win_update_ui.c.o
.PHONY : src/win/ui_win_update_ui.c.o

src/win/ui_win_update_ui.i: src/win/ui_win_update_ui.c.i

.PHONY : src/win/ui_win_update_ui.i

# target to preprocess a source file
src/win/ui_win_update_ui.c.i:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_win_update_ui.c.i
.PHONY : src/win/ui_win_update_ui.c.i

src/win/ui_win_update_ui.s: src/win/ui_win_update_ui.c.s

.PHONY : src/win/ui_win_update_ui.s

# target to generate assembly for a file
src/win/ui_win_update_ui.c.s:
	$(MAKE) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/src/win/ui_win_update_ui.c.s
.PHONY : src/win/ui_win_update_ui.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ui"
	@echo "... src/button/ui_button.o"
	@echo "... src/button/ui_button.i"
	@echo "... src/button/ui_button.s"
	@echo "... src/button/ui_simple_button.o"
	@echo "... src/button/ui_simple_button.i"
	@echo "... src/button/ui_simple_button.s"
	@echo "... src/button/ui_text_area.o"
	@echo "... src/button/ui_text_area.i"
	@echo "... src/button/ui_text_area.s"
	@echo "... src/button/ui_text_entry_button.o"
	@echo "... src/button/ui_text_entry_button.i"
	@echo "... src/button/ui_text_entry_button.s"
	@echo "... src/draw/draw.o"
	@echo "... src/draw/draw.i"
	@echo "... src/draw/draw.s"
	@echo "... src/draw/draw_shape.o"
	@echo "... src/draw/draw_shape.i"
	@echo "... src/draw/draw_shape.s"
	@echo "... src/event/ui_event.o"
	@echo "... src/event/ui_event.i"
	@echo "... src/event/ui_event.s"
	@echo "... src/frame/ui_frame.o"
	@echo "... src/frame/ui_frame.i"
	@echo "... src/frame/ui_frame.s"
	@echo "... src/frame/ui_simple_frame.o"
	@echo "... src/frame/ui_simple_frame.i"
	@echo "... src/frame/ui_simple_frame.s"
	@echo "... src/load_ui/ui_check_line_name.o"
	@echo "... src/load_ui/ui_check_line_name.i"
	@echo "... src/load_ui/ui_check_line_name.s"
	@echo "... src/load_ui/ui_general_get.o"
	@echo "... src/load_ui/ui_general_get.i"
	@echo "... src/load_ui/ui_general_get.s"
	@echo "... src/load_ui/ui_get_b_type.o"
	@echo "... src/load_ui/ui_get_b_type.i"
	@echo "... src/load_ui/ui_get_b_type.s"
	@echo "... src/load_ui/ui_get_flags.o"
	@echo "... src/load_ui/ui_get_flags.i"
	@echo "... src/load_ui/ui_get_flags.s"
	@echo "... src/load_ui/ui_get_type.o"
	@echo "... src/load_ui/ui_get_type.i"
	@echo "... src/load_ui/ui_get_type.s"
	@echo "... src/load_ui/ui_load.o"
	@echo "... src/load_ui/ui_load.i"
	@echo "... src/load_ui/ui_load.s"
	@echo "... src/load_ui/ui_parse_button.o"
	@echo "... src/load_ui/ui_parse_button.i"
	@echo "... src/load_ui/ui_parse_button.s"
	@echo "... src/load_ui/ui_parse_buttons.o"
	@echo "... src/load_ui/ui_parse_buttons.i"
	@echo "... src/load_ui/ui_parse_buttons.s"
	@echo "... src/load_ui/ui_parse_frame.o"
	@echo "... src/load_ui/ui_parse_frame.i"
	@echo "... src/load_ui/ui_parse_frame.s"
	@echo "... src/load_ui/ui_parse_frame_data.o"
	@echo "... src/load_ui/ui_parse_frame_data.i"
	@echo "... src/load_ui/ui_parse_frame_data.s"
	@echo "... src/load_ui/ui_parse_simple_button.o"
	@echo "... src/load_ui/ui_parse_simple_button.i"
	@echo "... src/load_ui/ui_parse_simple_button.s"
	@echo "... src/load_ui/ui_parse_simple_frame.o"
	@echo "... src/load_ui/ui_parse_simple_frame.i"
	@echo "... src/load_ui/ui_parse_simple_frame.s"
	@echo "... src/load_ui/ui_parse_text_area.o"
	@echo "... src/load_ui/ui_parse_text_area.i"
	@echo "... src/load_ui/ui_parse_text_area.s"
	@echo "... src/load_ui/ui_parse_text_entry_button.o"
	@echo "... src/load_ui/ui_parse_text_entry_button.i"
	@echo "... src/load_ui/ui_parse_text_entry_button.s"
	@echo "... src/load_ui/ui_parse_text_entry_cut.o"
	@echo "... src/load_ui/ui_parse_text_entry_cut.i"
	@echo "... src/load_ui/ui_parse_text_entry_cut.s"
	@echo "... src/load_ui/ui_parse_texture.o"
	@echo "... src/load_ui/ui_parse_texture.i"
	@echo "... src/load_ui/ui_parse_texture.s"
	@echo "... src/load_ui/ui_parse_type.o"
	@echo "... src/load_ui/ui_parse_type.i"
	@echo "... src/load_ui/ui_parse_type.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/shape/ui_rect.o"
	@echo "... src/shape/ui_rect.i"
	@echo "... src/shape/ui_rect.s"
	@echo "... src/texture/ui_draw_one_line_return.o"
	@echo "... src/texture/ui_draw_one_line_return.i"
	@echo "... src/texture/ui_draw_one_line_return.s"
	@echo "... src/texture/ui_draw_text_line.o"
	@echo "... src/texture/ui_draw_text_line.i"
	@echo "... src/texture/ui_draw_text_line.s"
	@echo "... src/texture/ui_draw_text_line_return.o"
	@echo "... src/texture/ui_draw_text_line_return.i"
	@echo "... src/texture/ui_draw_text_line_return.s"
	@echo "... src/texture/ui_draw_text_rect.o"
	@echo "... src/texture/ui_draw_text_rect.i"
	@echo "... src/texture/ui_draw_text_rect.s"
	@echo "... src/texture/ui_free_texture_set.o"
	@echo "... src/texture/ui_free_texture_set.i"
	@echo "... src/texture/ui_free_texture_set.s"
	@echo "... src/texture/ui_renderer.o"
	@echo "... src/texture/ui_renderer.i"
	@echo "... src/texture/ui_renderer.s"
	@echo "... src/texture/ui_text.o"
	@echo "... src/texture/ui_text.i"
	@echo "... src/texture/ui_text.s"
	@echo "... src/texture/ui_texture.o"
	@echo "... src/texture/ui_texture.i"
	@echo "... src/texture/ui_texture.s"
	@echo "... src/texture/ui_texture_list.o"
	@echo "... src/texture/ui_texture_list.i"
	@echo "... src/texture/ui_texture_list.s"
	@echo "... src/ui_error.o"
	@echo "... src/ui_error.i"
	@echo "... src/ui_error.s"
	@echo "... src/ui_init.o"
	@echo "... src/ui_init.i"
	@echo "... src/ui_init.s"
	@echo "... src/win/ui.o"
	@echo "... src/win/ui.i"
	@echo "... src/win/ui.s"
	@echo "... src/win/ui_call_button_function.o"
	@echo "... src/win/ui_call_button_function.i"
	@echo "... src/win/ui_call_button_function.s"
	@echo "... src/win/ui_display_buttons.o"
	@echo "... src/win/ui_display_buttons.i"
	@echo "... src/win/ui_display_buttons.s"
	@echo "... src/win/ui_display_frames.o"
	@echo "... src/win/ui_display_frames.i"
	@echo "... src/win/ui_display_frames.s"
	@echo "... src/win/ui_display_simple.o"
	@echo "... src/win/ui_display_simple.i"
	@echo "... src/win/ui_display_simple.s"
	@echo "... src/win/ui_display_text_area.o"
	@echo "... src/win/ui_display_text_area.i"
	@echo "... src/win/ui_display_text_area.s"
	@echo "... src/win/ui_display_text_entry.o"
	@echo "... src/win/ui_display_text_entry.i"
	@echo "... src/win/ui_display_text_entry.s"
	@echo "... src/win/ui_get_side_rect.o"
	@echo "... src/win/ui_get_side_rect.i"
	@echo "... src/win/ui_get_side_rect.s"
	@echo "... src/win/ui_mouse.o"
	@echo "... src/win/ui_mouse.i"
	@echo "... src/win/ui_mouse.s"
	@echo "... src/win/ui_resolve_buttons_event.o"
	@echo "... src/win/ui_resolve_buttons_event.i"
	@echo "... src/win/ui_resolve_buttons_event.s"
	@echo "... src/win/ui_resolve_text_entry_button.o"
	@echo "... src/win/ui_resolve_text_entry_button.i"
	@echo "... src/win/ui_resolve_text_entry_button.s"
	@echo "... src/win/ui_set_button_function.o"
	@echo "... src/win/ui_set_button_function.i"
	@echo "... src/win/ui_set_button_function.s"
	@echo "... src/win/ui_update_buttons.o"
	@echo "... src/win/ui_update_buttons.i"
	@echo "... src/win/ui_update_buttons.s"
	@echo "... src/win/ui_update_frames.o"
	@echo "... src/win/ui_update_frames.i"
	@echo "... src/win/ui_update_frames.s"
	@echo "... src/win/ui_win.o"
	@echo "... src/win/ui_win.i"
	@echo "... src/win/ui_win.s"
	@echo "... src/win/ui_win_size.o"
	@echo "... src/win/ui_win_size.i"
	@echo "... src/win/ui_win_size.s"
	@echo "... src/win/ui_win_update_ui.o"
	@echo "... src/win/ui_win_update_ui.i"
	@echo "... src/win/ui_win_update_ui.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

