#ifndef EVENT_FLAG_H
# define EVENT_FLAG_H

# include "SDL.h"

# define UI_WINEV_SHOWN SDL_WINDOWEVENT_SHOWN
# define UI_WINEV_MOVED SDL_WINDOWEVENT_MOVED
# define UI_WINEV_RESIZED SDL_WINDOWEVENT_RESIZED
# define UI_WINEV_MINIMIZED SDL_WINDOWEVENT_MINIMIZED
# define UI_WINEV_RESTORED SDL_WINDOWEVENT_RESTORED
# define UI_WINEV_ENTER SDL_WINDOWEVENT_ENTER
# define UI_WINEV_LEAVE SDL_WINDOWEVENT_LEAVE
# define UI_WINEV_CLOSE SDL_WINDOWEVENT_CLOSE

#endif