#ifndef RENDERER_FLAG_H
# define RENDERER_FLAG_H

# include "SDL.h"

# define UI_REND_SOFTWARE SDL_RENDERER_SOFTWARE
# define UI_REND_ACCELERATED SDL_RENDERER_ACCELERATED
# define UI_REND_VSYNC SDL_RENDERER_PRESENTVSYNC

#endif