#ifndef WINDOW_FLAG_H
# define WINDOW_FLAG_H

#include "SDL.h"

/**
 * Flags de Window
 */
# define UI_WIN_FULLSCREEN SDL_WINDOW_FULLSCREEN
# define UI_WIN_FULLSCREEN_DESK SDL_WINDOW_FULLSCREEN_DESKTOP
# define UI_WIN_SHOWN SDL_WINDOW_SHOWN
# define UI_WIN_HIDE SDL_WINDOW_HIDDEN
# define UI_WIN_BORDERLESS SDL_WINDOW_BORDERLESS
# define UI_WIN_RESIZABLE SDL_WINDOW_RESIZABLE
# define UI_WIN_MINI SDL_WINDOW_MINIMIZED
# define UI_WIN_MAXI SDL_WINDOW_MAXIMIZED
# define UI_WIN_MOUSE_FOCUS SDL_WINDOW_MOUSE_FOCUS
# define UI_WIN_INPUT_FOCUS SDL_WINDOW_INPUT_FOCUS
# define UI_WINPOS_CENTERED SDL_WINDOWPOS_CENTERED

#endif